### ISSUE TITLE
Update version to 3.2.3

### ISSUE THREAD

**Issue by evorios** [whyleee/Microsoft.jQuery.Unobtrusive.Ajax#2]
[subj](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/)

**Comment by whyleee** [comment]
Updated! But actually this version is the same as `3.2.2`, at least [NuGet package](https://www.nuget.org/packages/Microsoft.jQuery.Unobtrusive.Ajax/) contains the same code. I assume the version was updated on NuGet just in pair with `Microsoft.jQuery.Unobtrusive.Validation` package. So I just bumped the version number here.
